version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "develop"