updates:
  - package-ecosystem: "pnpm"
    directory: "/front"
    schedule:
      interval: "daily"
      target-branch: "develop"
  - package-ecosystem: "pnpm"
    directory: "/backend"
    schedule:
      interval: "daily"
      target-branch: "develop"