services:
  back:
    container_name: back
    restart: unless-stopped
    image: ghcr.io/tnfb/projet_sigl/backend:latest
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DB_HOST:
      DB_PORT:
      DB_USER:
      DB_PASSWORD:
      LOG_LEVEL: info
    volumes:
      - ~chemin de stockage machine hôte~/storage:/app/build/storage:rw

  phpmyadmin_sigl:
    container_name: phpmyadmin_sigl
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      PMA_HOST: 
      PMA_PORT: 
      PMA_ABSOLUTE_URI: ""
    ports:
      - 60000:80
