import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/user'
import bcrypt from 'bcrypt'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    await User.createMany([
      {
        email: 'liger@eseo.fr',
        password: await bcrypt.hash('LigerJ', 10),
        name: 'Admin',
        last_name: 'User',
        telephone: '1234567890',
        role: 'admins',
        token: null,
        expired_date: null,
      },
      {
        email: 'john@eseo.fr',
        password: await bcrypt.hash('JohnD', 10),
        name: 'John',
        last_name: 'Doe',
        telephone: '9876543210',
        role: 'apprentices',
        token: null,
        expired_date: null,
      },
      {
        email: 'orlando@eseo.fr',
        password: await bcrypt.hash('OrlandoP', 10),
        name: 'Orlando',
        last_name: 'Pastorice',
        telephone: '6666666666',
        role: 'apprentices',
        token: null,
        expired_date: null,
      },
      {
        email: 'killian@eseo.fr',
        password: await bcrypt.hash('KillianS', 10),
        name: 'Killian',
        last_name: 'Surugyai',
        telephone: '7777777777',
        role: 'apprentices',
        token: null,
        expired_date: null,
      },
      {
        email: 'michel@eseo.fr',
        password: await bcrypt.hash('MichelM', 10),
        name: 'Michel',
        last_name: 'Chelmi',
        telephone: '1234567890',
        role: 'apprentice_masters',
        token: null,
        expired_date: null,
      },
      {
        email: 'dupont@eseo.fr',
        password: await bcrypt.hash('DupontD', 10),
        name: 'Dupont',
        last_name: 'Pondut',
        telephone: '1234567890',
        role: 'apprentice_masters',
        token: null,
        expired_date: null,
      },
      {
        email: 'patrick@eseo.fr',
        password: await bcrypt.hash('PatrickP', 10),
        name: 'Patrick',
        last_name: 'Rickpat',
        telephone: '1234567890',
        role: 'apprentice_masters',
        token: null,
        expired_date: null,
      },
      {
        email: 'jon@eseo.fr',
        password: await bcrypt.hash('JonMcG', 10),
        name: 'Jon',
        last_name: 'McGordon',
        telephone: '1234567890',
        role: 'educational_tutors',
        token: null,
        expired_date: null,
      },
      {
        email: 'maissa@eseo.fr',
        password: await bcrypt.hash('MaissaS', 10),
        name: 'Maissa',
        last_name: 'Samais',
        telephone: '1234567890',
        role: 'educational_tutors',
        token: null,
        expired_date: null,
      },
      {
        email: 'jerome@eseo.fr',
        password: await bcrypt.hash('JeromeR', 10),
        name: 'Jerome',
        last_name: 'Romeje',
        telephone: '1234567890',
        role: 'educational_tutors',
        token: null,
        expired_date: null,
      },
      {
        email: 'professionals1@eseo.fr',
        password: await bcrypt.hash('professionals159', 10),
        name: 'professionals1',
        last_name: 'professionals1',
        telephone: '1234567890',
        role: 'professionals',
        token: null,
        expired_date: null,
      },
      {
        email: 'professionals2@eseo.fr',
        password: await bcrypt.hash('professionals258', 10),
        name: 'professionals2',
        last_name: 'professionals2',
        telephone: '1234567890',
        role: 'professionals',
        token: null,
        expired_date: null,
      },
      {
        email: 'professionals3@eseo.fr',
        password: await bcrypt.hash('professionals357', 10),
        name: 'professionals3',
        last_name: 'professionals3',
        telephone: '1234567890',
        role: 'professionals',
        token: null,
        expired_date: null,
      },
      {
        email: 'teachers1@eseo.fr',
        password: await bcrypt.hash('teachers1', 10),
        name: 'teachers1',
        last_name: 'teachers1',
        telephone: '1234567890',
        role: 'teachers',
        token: null,
        expired_date: null,
      },
      {
        email: 'teachers2@eseo.fr',
        password: await bcrypt.hash('teachers2', 10),
        name: 'teachers2',
        last_name: 'teachers2',
        telephone: '1234567890',
        role: 'teachers',
        token: null,
        expired_date: null,
      },
    ])
  }
}
