# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - journal-formation

on:
  push:
    branches:
      - Azure-CI-CD
  workflow_dispatch:

env:
  ARTIFACT_VERSION: 2.${{ github.run_number }}.tar

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the Dockerfile
        run: |
          cd backend
          docker build -t backend:${{ env.ARTIFACT_VERSION }} .

      - name: Export the image
        run: docker save backend:${{ env.ARTIFACT_VERSION }} > backend.tar

      - name: Upload the image
        uses: actions/upload-artifact@v4
        with:
            name: backend-${{ env.ARTIFACT_VERSION }}
            path: backend.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'develop'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-${{ env.ARTIFACT_VERSION }}

      - name: Login with Managed Identity
        uses: azure/login@v1
        with:
          managed-identity-client-id: ${{ secrets.AZURE_MANAGED_CLIENT_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'journaldeformation'
          package: backend.tar
          slot-name: 'production'