# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - journal-formation

on:
  push:
    branches:
      - Azure-CI-CD
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move to backend directory
        run: cd backend

      - name: Run the Dockerfile
        run: |
          commit_count=$(git rev-list --count HEAD)
          docker build -t backend:2.1.$commit_count .

      - name: Export the image
        run: docker save backend:2.1.$commit_count > backend.tar

      - name: Upload the image
        uses: actions/upload-artifact@v4
        with:
            name: backend-2.1.$(git rev-list --count HEAD).tar

  deploy:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-2.1.$(git rev-list --count HEAD).tar

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'journaldeformation'
          package: backend-2.1.$(git rev-list --count HEAD).tar
          slot-name: 'production'