name: Package-cleaner

on:
  push:
    branches:
      - package-cleaner

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run the Dockerfile
        run: |
          cd front
          docker build .